[package]
name = "janq"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.32", features = ["rt", "macros", "sync", "time", "signal", "process"] }
zbus = { version = "4.1", features = ["tokio"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
anyhow = "1.0"
dirs = "5.0"
notify = "6.1"
image = { version = "0.24", default-features = false, features = ["png", "ico"] }
fs2 = "0.4"
clap = { version = "4.4", features = ["derive"] }
serde_json = "1.0"
indexmap = { version = "2.0", features = ["serde"] }

[build-dependencies]
winres = "0.1"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_Graphics_Gdi",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_ProcessStatus",
    "Win32_UI_HiDpi",
    "Win32_System_Console",
    "Win32_Graphics_DirectComposition",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
], default-features = false }
tray-icon = "0.14"
tao = "0.26"
winit = "0.29"
tokio = { version = "1.32", features = ["rt-multi-thread"] }
global-hotkey = "0.5"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true
opt-level = 3
overflow-checks = false
